// ============================================================
// SILLAGE — name-matched photo sourcing (Wikimedia Commons)
// For each scent, search Commons by "Brand Name", pick a clean
// portrait JPEG, download it to public/photos/<id>.jpg, and
// regenerate src/data/photoIds.ts. Anything not found falls
// back to the rendered bottle (BottleVisual).
//
// Uses curl (Commons' image CDN 403s plain programmatic UAs).
// Run: node scripts/source-photos.mjs
// ============================================================

import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync, statSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const OUT = join(root, 'public', 'photos');
mkdirSync(OUT, { recursive: true });

const { RAW } = await import(join(root, 'src/data/catalogData.ts'));

const UA = 'SillageDemo/1.0 (educational demo; contact@example.org)';
const BAD = /campaign|advert|poster|logo|store|shelf|model|wikipedia|magazine|billboard|mannequin|drawing|patent|box set/i;

function curlJSON(url) {
  try {
    const out = execSync(`curl -s -m 25 -H ${JSON.stringify('User-Agent: ' + UA)} ${JSON.stringify(url)}`, {
      encoding: 'utf8',
      maxBuffer: 20 * 1024 * 1024,
    });
    return JSON.parse(out);
  } catch {
    return null;
  }
}

function searchCommons(term) {
  const params = new URLSearchParams({
    action: 'query',
    generator: 'search',
    gsrsearch: term,
    gsrnamespace: '6',
    gsrlimit: '8',
    prop: 'imageinfo',
    iiprop: 'url|mime|size',
    iiurlwidth: '900',
    format: 'json',
  });
  const data = curlJSON('https://commons.wikimedia.org/w/api.php?' + params.toString());
  const pages = data?.query?.pages;
  if (!pages) return [];
  return Object.values(pages)
    .map((p) => ({ title: (p.title || '').slice(5), ii: (p.imageinfo || [])[0] }))
    .filter((x) => x.ii && x.ii.mime === 'image/jpeg' && x.ii.thumbwidth && x.ii.thumbheight)
    .filter((x) => {
      const ar = x.ii.thumbwidth / x.ii.thumbheight;
      return ar >= 0.45 && ar <= 1.5 && !BAD.test(x.title);
    });
}

function download(url, dest) {
  try {
    execSync(
      `curl -s -m 30 -o ${JSON.stringify(dest)} -H ${JSON.stringify('User-Agent: ' + UA)} -H ${JSON.stringify('Accept: image/jpeg,*/*')} ${JSON.stringify(url)}`,
      { stdio: 'ignore' },
    );
    return existsSync(dest) && statSync(dest).size > 9000;
  } catch {
    return false;
  }
}

const have = [];
let i = 0;
for (const p of RAW) {
  i++;
  const terms = [`${p.brand} ${p.name}`, `${p.name} ${p.brand} perfume`];
  let picked = null;
  for (const t of terms) {
    const hits = searchCommons(t);
    // prefer a hit whose title shares a word with the scent name
    const nameWords = p.name.toLowerCase().replace(/[^a-z0-9 ]/g, '').split(/\s+/).filter((w) => w.length > 2);
    const scored = hits
      .map((h) => {
        const tl = h.title.toLowerCase();
        const score = nameWords.reduce((s, w) => s + (tl.includes(w) ? 1 : 0), 0);
        return { ...h, score };
      })
      .sort((a, b) => b.score - a.score);
    if (scored[0]) {
      picked = scored[0];
      if (scored[0].score > 0) break; // good name match — stop
    }
  }
  if (picked && download(picked.ii.thumburl, join(OUT, `${p.id}.jpg`))) {
    have.push(p.id);
    process.stdout.write(`  ✓ ${p.id}  ←  ${picked.title}\n`);
  } else {
    process.stdout.write(`  ·  ${p.id}  (render fallback)\n`);
  }
}

// write photoIds.ts
const idsLiteral = have.map((id) => `  '${id}',`).join('\n');
writeFileSync(
  join(root, 'src/data/photoIds.ts'),
  `// ============================================================
// SILLAGE — ids that have a real, name-matched product photo at
// public/photos/<id>.jpg. GENERATED by scripts/source-photos.mjs.
// Anything NOT in this set falls back to the rendered bottle.
// ============================================================

export const PHOTO_IDS = new Set<string>([
${idsLiteral}
]);
`,
);

// contact sheet for review
const tiles = have
  .map((id) => `<div class=t><img src="/photos/${id}.jpg"><span>${id}</span></div>`)
  .join('');
writeFileSync(
  join(root, 'public', '_photos.html'),
  `<!doctype html><meta charset=utf8><style>body{margin:0;background:#FAF8F4;font-family:monospace;padding:10px}.g{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.t{background:#fff;border:1px solid #ddd;border-radius:8px;overflow:hidden}.t img{width:100%;height:150px;object-fit:contain;background:#f4f2ec;display:block}.t span{display:block;font-size:9px;padding:3px;color:#333;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}</style><div class=g>${tiles}</div>`,
);

console.log(`\nDownloaded ${have.length}/${RAW.length} name-matched photos. ${RAW.length - have.length} use the rendered fallback.`);
